-- MySQL Script generated by MySQL Workbench
-- Sun Nov 18 17:55:02 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_telemarketing
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_telemarketing
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_telemarketing` DEFAULT CHARACTER SET utf8 ;
USE `db_telemarketing` ;

-- -----------------------------------------------------
-- Table `db_telemarketing`.`tb_pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_telemarketing`.`tb_pessoa` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `pai` VARCHAR(60) NULL DEFAULT NULL,
  `mae` VARCHAR(60) NULL DEFAULT NULL,
  `cep` VARCHAR(9) NULL DEFAULT NULL,
  `endereco` VARCHAR(100) NULL DEFAULT NULL,
  `bairro` VARCHAR(40) NULL DEFAULT NULL,
  `celular` VARCHAR(14) NOT NULL COMMENT '(21)99999-9999',
  `residencial` VARCHAR(14) NOT NULL,
  `cel_pai` VARCHAR(14) NULL,
  `cel_mae` VARCHAR(14) NULL,
  `ativo` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `db_telemarketing`.`tb_curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_telemarketing`.`tb_curso` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(30) NOT NULL,
  `descricao` VARCHAR(100) NOT NULL,
  `ativo` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `db_telemarketing`.`tb_ligacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_telemarketing`.`tb_ligacao` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `inicio` TIME NOT NULL,
  `fim` TIME NOT NULL,
  `data_ligacao` DATE NOT NULL,
  `Observacoes` VARCHAR(100) NOT NULL,
  `pessoa_id` INT(11) NOT NULL,
  `ativo` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_ligacao_tb_pessoa1_idx` (`pessoa_id` ASC),
  CONSTRAINT `fk_tb_ligacao_tb_pessoa1`
    FOREIGN KEY (`pessoa_id`)
    REFERENCES `db_telemarketing`.`tb_pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `db_telemarketing`.`tb_ligacao_oferece_curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_telemarketing`.`tb_ligacao_oferece_curso` (
  `ligacao_id` INT(11) NOT NULL,
  `curso_id` INT(11) NOT NULL,
  `manha` TINYINT(1) NOT NULL DEFAULT 0,
  `tarde` TINYINT(1) NOT NULL DEFAULT 0,
  `noite` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`ligacao_id`, `curso_id`),
  INDEX `fk_tb_ligacao_has_tb_curso_tb_curso1_idx` (`curso_id` ASC),
  INDEX `fk_tb_ligacao_has_tb_curso_tb_ligacao1_idx` (`ligacao_id` ASC),
  CONSTRAINT `fk_tb_ligacao_has_tb_curso_tb_ligacao1`
    FOREIGN KEY (`ligacao_id`)
    REFERENCES `db_telemarketing`.`tb_ligacao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_ligacao_has_tb_curso_tb_curso1`
    FOREIGN KEY (`curso_id`)
    REFERENCES `db_telemarketing`.`tb_curso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
